### ISSUE TITLE
Hosted Example asking for password

### ISSUE THREAD

**Issue by Stoffberg** [jneeee/uspb#2]
Hi,

I'm trying to use the demo but it is asking for a password...
What can I do?

**Comment by jneeee** [comment]
Hi!
I got attacked yesterday. So I add a password to protect it.
I will email you the password.

**Comment by diomed** [comment]
ummm... how can anyone try demo if we dont know password?

**Comment by jneeee** [comment]
> ummm... how can anyone try demo if we dont know password?

Hi, As demo Index page shows, you can try: https://uspb.deno.dev/s/1xSzh will jump to github
https://uspb.deno.dev/s/5pUOC will show text in a card
That's all it does.

**Comment by Stoffberg** [comment]
@jneeee If I create a pull request and you add me to the project on Deno Deploy I'll implement rate limiting on the API so that the project works without a password.

Is that something you'd be interested in doing? Alternatively we can schedule a call to just exchange the necessary keys for the pull request to work.

Let me know if that sounds like a viable solution to you.

**Comment by jneeee** [comment]
Hi, @Stoffberg 
That sounds great. Thank you! Feel free to create a PR to master branch. The deno project will deploy the master branch automaticly.

My concern is that if I'm still attacked after that, I might deploy a password-protected version at uspb.deno.dev (use another password-protected branch) and keep the rate limiting version on the master branch.
This gives two options for people interested in deploying uspb themselves.

**Comment by jneeee** [comment]
the password removed
